"""update_users_table

Revision ID: 04147b6e657d
Revises: 91f9b6627ccc
Create Date: 2020-12-18 11:58:24.154938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04147b6e657d'
down_revision = '91f9b6627ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_ibfk_2', 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_ibfk_2', 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
