"""update_users_table

Revision ID: 1ad52b6d337b
Revises: b0a526a650df
Create Date: 2020-12-18 12:03:29.577283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad52b6d337b'
down_revision = 'b0a526a650df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
