"""update_users_table

Revision ID: 39adff1b97a9
Revises: 91c3b186d5b5
Create Date: 2020-12-18 11:40:46.498107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39adff1b97a9'
down_revision = '91c3b186d5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
