"""update_users_table

Revision ID: 3bd63c80ff70
Revises: d9d66e30d103
Create Date: 2020-12-18 11:56:59.091043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bd63c80ff70'
down_revision = 'd9d66e30d103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_ibfk_2', 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_ibfk_2', 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
