"""aaa

Revision ID: 43a52d7b66ef
Revises: cef376fce1ad
Create Date: 2020-12-19 22:24:28.799797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a52d7b66ef'
down_revision = 'cef376fce1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
