"""update_users_table

Revision ID: 64eca55fc161
Revises: eff1c3784602
Create Date: 2020-12-18 11:44:18.598736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eca55fc161'
down_revision = 'eff1c3784602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
