"""update_users_table

Revision ID: 69dbf969b614
Revises: 04147b6e657d
Create Date: 2020-12-18 11:59:09.098870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69dbf969b614'
down_revision = '04147b6e657d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###
