"""update_users_table

Revision ID: 7f3f395e0a9d
Revises: 984ab2dfeec2
Create Date: 2020-12-18 12:00:27.579850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3f395e0a9d'
down_revision = '984ab2dfeec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
