"""update_users_table

Revision ID: 928bdbe551b8
Revises: 1ad52b6d337b
Create Date: 2020-12-18 12:04:16.006825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928bdbe551b8'
down_revision = '1ad52b6d337b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
