"""update_users_table

Revision ID: 984ab2dfeec2
Revises: 69dbf969b614
Create Date: 2020-12-18 11:59:34.169844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984ab2dfeec2'
down_revision = '69dbf969b614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
