"""aaa

Revision ID: cef376fce1ad
Revises: 928bdbe551b8
Create Date: 2020-12-19 22:23:45.529209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef376fce1ad'
down_revision = '928bdbe551b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
