"""update_users_table

Revision ID: d9d66e30d103
Revises: 64eca55fc161
Create Date: 2020-12-18 11:50:11.507762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d66e30d103'
down_revision = '64eca55fc161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
