"""update_users_table

Revision ID: df5ef95bd6b1
Revises: 39adff1b97a9
Create Date: 2020-12-18 11:41:31.324532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5ef95bd6b1'
down_revision = '39adff1b97a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
